[project]
name = "calc_num_2023"
version = "0.1.0"
description = "Curso de Cálculo Numérico - UFABC "
authors = ["Pedro Mendes <pedrohrmendes@proton.me>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
readme = "README.md"
repository = "https://github.com/phrmendes/calc_num_2023"

[dependencies]
ipython = ">=8.21.0,<8.22"
jupyterlab = ">=4.1.0,<4.2"
jupyterlab_vim = ">=4.1.3,<4.2"
matplotlib = ">=3.8.2,<3.9"
numpy = ">=1.26.4,<1.27"
python = ">=3.12.1,<3.13"
python-lsp-ruff = ">=2.0.2,<2.1"
python-lsp-server = ">=1.10.0,<1.11"
ruff = ">=0.1.15,<0.2"
jupyterlab-lsp = ">=5.0.3,<5.1"
